# Generated by Django 2.2 on 2019-04-10 00:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fieldwork.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='task name')),
                ('slug', models.SlugField(blank=True, help_text='leave blank or your-brand-name', null=True, unique=True)),
                ('merge_into_pile', models.BooleanField(default=False)),
                ('merge_with_pile', models.CharField(blank=True, max_length=20, null=True)),
                ('new_pile_name', models.CharField(blank=True, help_text='only if mixing piles', max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=fieldwork.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('days', models.IntegerField(default=0, verbose_name='days since turned')),
                ('must_turn_pile', models.BooleanField(default=False)),
                ('must_water_now', models.BooleanField(default=False)),
                ('is_pile_ready', models.BooleanField(default=False)),
                ('turn_cycle', models.IntegerField(default=0)),
                ('times_watered', models.IntegerField(default=0)),
                ('turned', models.BooleanField(default=False)),
                ('watered', models.BooleanField(default=False)),
                ('humidity_measured_with', models.CharField(choices=[('O', 'observation'), ('D', 'device'), ('T', 'thermometer')], max_length=1)),
                ('temperature_measured_with', models.CharField(choices=[('O', 'observation'), ('D', 'device'), ('T', 'thermometer')], max_length=1)),
                ('celsius', models.BooleanField(default=False)),
                ('core_temperature_readings', models.CharField(blank=True, help_text='comma separated temperature measurements, no white space', max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('core_humidity_readings', models.CharField(blank=True, help_text='comma separated humidity measurements, no white space', max_length=155, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('average_temperature', models.IntegerField(blank=True, null=True)),
                ('average_humidity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'field data',
                'verbose_name_plural': 'fields data',
                'ordering': ['user', '-timestamp', 'created'],
            },
        ),
        migrations.CreateModel(
            name='FieldWorkView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.View')),
            ],
            bases=('analytics.view',),
        ),
    ]
