# Generated by Django 2.2 on 2019-04-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
        ('engine_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engines',
            name='engineer',
            field=models.ManyToManyField(blank=True, to='personnel.Engineer'),
        ),
        migrations.AddField(
            model_name='engines',
            name='genset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.GenSet'),
        ),
        migrations.AddField(
            model_name='engines',
            name='genset2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.GenSet2'),
        ),
        migrations.AddField(
            model_name='engines',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.MainEngine'),
        ),
        migrations.AddField(
            model_name='engines',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.PortEngine'),
        ),
        migrations.AddField(
            model_name='engines',
            name='port2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.PortEngine2'),
        ),
        migrations.AddField(
            model_name='engines',
            name='port3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.PortEngine3'),
        ),
        migrations.AddField(
            model_name='engines',
            name='starboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.StarboardEngine'),
        ),
        migrations.AddField(
            model_name='engines',
            name='starboard2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.StarboardEngine2'),
        ),
        migrations.AddField(
            model_name='engines',
            name='starboard3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.StarboardEngine3'),
        ),
        migrations.AddField(
            model_name='engines',
            name='tool_and_equipment',
            field=models.ManyToManyField(blank=True, to='engine_room.Tools'),
        ),
        migrations.AddField(
            model_name='engines',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centerengine',
            name='serial_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='serial_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Asset'),
        ),
    ]
