# Generated by Django 2.2 on 2019-04-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_auto_20190330_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('shop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shops.Shop')),
                ('customers', models.ManyToManyField(related_name='provider', to='shops.Shop')),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
            },
            bases=('shops.shop',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Commercial Name', max_length=60, null=True)),
                ('contact', models.CharField(blank=True, help_text='store contact', max_length=60, null=True)),
                ('content', models.TextField(help_text='provider or supplier of what?', null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('url', models.URLField(blank=True, help_text='website', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='shops.Shop')),
                ('merchant_category', models.CharField(choices=[('CO', 'consumables'), ('PE', 'perishables'), ('SE', 'service provider'), ('ME', 'merchandise'), ('SM', 'service & merchandise'), ('ED', 'digital services'), ('SA', 'sustainable agriculture'), ('IN', 'insurance')], default='service & merchandise', max_length=2)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['merchant_category', 'address', 'title', 'contact', '-update'],
            },
        ),
    ]
