# Generated by Django 2.2 on 2019-04-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iotsensor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload_location')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scrape', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorIoT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='sensoriot', max_length=65)),
                ('slug', models.SlugField(blank=True, help_text='leave blank, or unique name', null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('address', models.GenericIPAddressField(blank=True, help_text='ip address', null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=iotsensor.models.upload_sensor_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField(verbose_name='description and condition')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.CharField(choices=[('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996')], default='2019', max_length=4)),
                ('serial_number', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='serial number')),
                ('registration', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='tag')),
                ('used_for', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('publish', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='person responsible for', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish', 'brand', 'model', 'year', 'user'],
            },
        ),
    ]
