# Generated by Django 2.2 on 2019-04-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofasset',
            name='location_of_asset',
            field=models.ForeignKey(blank=True, help_text='where is the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.BuildingLocation'),
        ),
        migrations.AddField(
            model_name='typeofasset',
            name='marine_vessel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.MarineVessel'),
        ),
        migrations.AddField(
            model_name='typeofasset',
            name='tool',
            field=models.ManyToManyField(blank=True, to='assets.Equipment'),
        ),
        migrations.AddField(
            model_name='typeofasset',
            name='user',
            field=models.ForeignKey(blank=True, help_text='person responsible for', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='throughhull',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Parts'),
        ),
        migrations.AddField(
            model_name='marinevessel',
            name='asset',
            field=models.ManyToManyField(to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='marinevessel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.MarineVesselManufacturer'),
        ),
    ]
