# Generated by Django 2.2 on 2019-04-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('assets', '0002_auto_20190409_1707'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engine_room', '0002_auto_20190409_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Command Order', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('order_number', models.PositiveIntegerField(default=0)),
                ('purchase_number', models.CharField(max_length=25, unique=True)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('product_number', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost_of_item', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('for_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.TypeOfAsset')),
                ('for_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine_room.Engines')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.Supplier')),
                ('user', models.ForeignKey(default=1, help_text='ordered by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-date_ordered'],
            },
        ),
    ]
