# Generated by Django 2.1.5 on 2019-01-22 03:30
from django.contrib.gis.db import models


class ZipCode(models.Model):
    code = models.CharField(max_length=5)

    def __str__(self):
        return str(self.code)


class Elevation(models.Model):
    name = models.CharField(max_length=100)
    rast = models.RasterField(blank=True, null=True)


class Shop(models.Model):
    # provides location for providers
    location = models.PointField()
    poly = models.PolygonField(blank=True, null=True)

    county = models.CharField(max_length=60, null=True, blank=True)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    zip_code = models.ForeignKey(ZipCode, on_delete=models.SET_NULL, null=True, blank=True)
    elevation = models.ForeignKey(Elevation, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.address)
