from django.urls import path, re_path

from .views import (
    asset_create, asset_detail, asset_list, asset_update,
    asset_delete, asset_asset_create, asset_asset_detail,
    asset_asset_update, asset_asset_delete, parts_detail,
    parts_create, parts_update, parts_delete,
    marine_asset_create, marine_asset_detail, marine_asset_list,
    marine_asset_update, marine_asset_delete,
    land_asset_create, land_asset_detail, land_asset_list,
    land_asset_update, land_asset_delete,
    equipment_asset_create, equipment_asset_detail,
    equipment_asset_list, equipment_asset_update,
    equipment_asset_delete,
    marine_manufacturer_create, marine_manufacturer_detail,
    marine_manufacturer_update, marine_manufacturer_delete,
    marine_model_create,  marine_model_detail, marine_model_update, marine_model_delete,
    car_manufacturer_create,
    car_model_create, car_manufacturer_detail, car_manufacturer_update, car_manufacturer_delete,
    car_model_detail, car_model_update, car_model_delete,
    equipment_manufacturer_create,
    equipment_model_create, equipment_manufacturer_detail, equipment_manufacturer_update,
    equipment_manufacturer_delete, equipment_model_detail,
    equipment_model_update, equipment_model_delete, through_hull_model_create,
    through_hull_detail, through_hull_update, through_hull_delete
)


app_name = 'assets'
urlpatterns = [
    path('', asset_list, name='list'),
    path('(<slug:slug>)/', asset_detail, name='detail'),
    path('(<slug:slug>)/edit/', asset_update, name='update'),
    path('(<slug:slug>)/delete/', asset_delete, name='delete'),
    path('create/', asset_create, name='create'),

    re_path('asset/', asset_asset_create, name='asset_create'),
    re_path('asset/(<int:pk>)', asset_asset_detail, name='asset_detail'),
    re_path('asset/(<int:pk>)/edit/', asset_asset_update, name='asset_update'),
    re_path('asset/(<int:pk>)/delete', asset_asset_delete, name='asset_delete'),
    path('parts/', parts_create, name='parts_create'),
    re_path('parts/(<int:pk>)', parts_detail, name='parts_detail'),
    re_path('parts/(<int:pk>)/edit/', parts_update, name='parts_update'),
    re_path('parts/(<int:pk>)/delete', parts_delete, name='parts_delete'),

    path('marine/', marine_asset_list, name='marine_list'),
    re_path('marine/create/', marine_asset_create, name='marine_create'),
    re_path('marine/(<slug:slug>)/', marine_asset_detail, name='marine_detail'),
    re_path('marine/(<slug:slug>)/edit/', marine_asset_update, name='marine_update'),
    re_path('marine/(<slug:slug>)/delete/', marine_asset_delete, name='marine_delete'),
    path('marine/manufacturer/', marine_manufacturer_create, name='marine_manufacturer_create'),
    re_path('marine/manufacturer/(<int:pk>)', marine_manufacturer_detail, name='marine-manufacturer_detail'),
    re_path('marine/manufacturer/(<int:pk>)/edit/', marine_manufacturer_update, name='marine_manufacturer_update'),
    re_path('marine/manufacturer/(<int:pk>)/delete', marine_manufacturer_delete, name='marine_manufacturer_delete'),
    re_path('marine/model/', marine_model_create, name='marine_model_create'),
    re_path('marine/model/(<int:pk>)', marine_model_detail, name='marine_model_detail'),
    re_path('marine/model/(<int:pk>)/edit/', marine_model_update, name='marine_model_update'),
    re_path('marine/model/(<int:pk>)/delete', marine_model_delete, name='marine_model_delete'),

    path('land/', land_asset_list, name='land_list'),
    re_path('land/create/', land_asset_create, name='land_create'),
    re_path('land/(<slug:slug>)/', land_asset_detail, name='land_detail'),
    re_path('land/(<slug:slug>)/edit/', land_asset_update, name='land_update'),
    re_path('land/(<slug:slug>)/delete/', land_asset_delete, name='land_delete'),
    path('land/manufacturer/', car_manufacturer_create, name='land_manufacturer_create'),
    re_path('land/manufacturer/(<int:pk>)', car_manufacturer_detail, name='land_manufacturer_detail'),
    re_path('land/manufacturer/(<int:pk>)/edit/', car_manufacturer_update, name='land_manufacturer_update'),
    re_path('land/manufacturer/(<int:pk>)/delete', car_manufacturer_delete, name='land_manufacturer_delete'),
    path('land/model/', car_model_create, name='land_model_create'),
    re_path('land/model/(<int:pk>)', car_model_detail, name='land_model_detail'),
    re_path('land/model/(<int:pk>)/edit/', car_model_update, name='land_model_update'),
    re_path('land/model/(<int:pk>)/delete', car_model_delete, name='land_model_delete'),

    path('equipment/', equipment_asset_list, name='equipment_list'),
    re_path('equipment/create/', equipment_asset_create, name='equipment_create'),
    re_path('equipment/(<slug:slug>)/', equipment_asset_detail, name='equipment_detail'),
    re_path('equipment/(<slug:slug>)/edit/', equipment_asset_update, name='equipment_update'),
    re_path('equipment/(<slug:slug>)/delete/', equipment_asset_delete, name='equipment_delete'),
    re_path('equipment/manufacturer/', equipment_manufacturer_create, name='equipment_manufacturer_create'),
    re_path('equipment/manufacturer/(<int:pk>)', equipment_manufacturer_detail, name='equipment_manufacturer_detail'),
    re_path('equipment/manufacturer/(<int:pk>)/edit/', equipment_manufacturer_update, name='equipment_manufacturer_update'),
    re_path('equipment/manufacturer/(<int:pk>)/delete', equipment_manufacturer_delete, name='equipment_manufacturer_delete'),
    path('equipment/model/', equipment_model_create, name='equipment_model_create'),
    re_path('equipment/model/(<int:pk>)', equipment_model_detail, name='equipment_model_detail'),
    re_path('equipment/model/(<int:pk>)/edit/', equipment_model_update, name='equipment_model_update'),
    re_path('equipment/model/(<int:pk>)/delete', equipment_model_delete, name='equipment_model_delete'),

    path('through-hull/', through_hull_model_create, name='through_hull_create'),
    re_path('through-hull/(<int:pk>)', through_hull_detail, name='through_hull_detail'),
    re_path('through-hull/(<int:pk>)/edit/', through_hull_update, name='through_hull_update'),
    re_path('through-hull/(<int:pk>)/delete', through_hull_delete, name='through_hull_delete'),

]
