from django import forms


class ServiceScheduleForm(forms.Form):
    repeated_short_trips_less_than_5_miles = forms.BooleanField()
    repeated_short_trips_less_than_10_miles_outside_below_freezing = forms.BooleanField()
    hot_weather_stop_and_go_traffic = forms.BooleanField()
    extensive_idling_and_or_low_speed_driving_for_long_distances = forms.BooleanField()
    driving_in_dusty_conditions = forms.BooleanField()
    driving_on_rough_muddy_or_salt_spread_roads = forms.BooleanField()
    towing_a_trailer_or_driving_with_a_car_top_carrier_installed = forms.BooleanField()

    engine_oil_miles = forms.IntegerField()
    engine_oil_months = forms.IntegerField()
    engine_oil_filter_miles = forms.IntegerField()
    engine_oil_filter_months = forms.IntegerField()
    air_cleaner_filter = forms.IntegerField()
    air_cleaner_months = forms.IntegerField()
    vapor_lines_miles = forms.IntegerField()
    vapor_lines_months = forms.IntegerField()
    fuel_lines_miles = forms.IntegerField()
    fuel_lines_months = forms.IntegerField()
    fuel_filter_miles = forms.IntegerField()
    fuel_filter_months = forms.IntegerField()
    engine_coolant_miles = forms.IntegerField()
    engine_coolant_months = forms.IntegerField()
    drive_belts_miles = forms.IntegerField()
    drive_belts_months = forms.IntegerField()
    spark_plugs_miles = forms.IntegerField()
    spark_plugs_months = forms.IntegerField()
    timing_belt_miles = forms.IntegerField()
    timing_belt_months = forms.IntegerField()

    brake_lines_and_cables = forms.IntegerField()
    brake_lines_and_cables_months = forms.IntegerField()
    brake_pads_disc_drums_and_linings = forms.IntegerField()
    brake_pads_disc_drums_and_linings_months = forms.IntegerField()
    four_wheel_drive_transfer_fluid_differential_gear_oil = forms.IntegerField()
    four_wheel_drive_transfer_fluid_differential_gear_oil_months = forms.IntegerField()
    limited_slip_differential_gear_oil = forms.IntegerField()
    limited_slip_differential_gear_oil_months = forms.IntegerField()
    exhaust_system = forms.IntegerField()
    exhaust_system_months = forms.IntegerField()
    drive_shaft_boots_and_propeller_shaft = forms.IntegerField()
    drive_shaft_boots_and_propeller_shaft_months = forms.IntegerField()
    propeller_shaft_grease = forms.IntegerField()
    propeller_shaft_grease_months = forms.IntegerField()
    steering_gear_and_suspension_parts = forms.IntegerField()
    steering_gear_and_suspension_parts_months = forms.IntegerField()
    front_wheel_bearing_grease = forms.IntegerField()
    front_wheel_bearing_grease_months = forms.IntegerField()
    supplemental_air_bag_system = forms.IntegerField()
    supplemental_air_bag_system_months = forms.IntegerField()

    odometer_reading = forms.DecimalField()
    in_miles = forms.BooleanField()
    in_kilometers = forms.BooleanField()
    in_hours = forms.BooleanField()
