# Generated by Django 2.2 on 2019-04-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Bulk', max_length=60, unique=True, verbose_name='type of compost')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_name', models.CharField(help_text='make unique, your brand + pile name', max_length=60, unique=True, verbose_name='pile name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='upload_location', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('observation', models.CharField(default='none', max_length=120)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('ready_to_use', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('category_value', models.IntegerField(default=50, help_text='usefull for commercial use', verbose_name='price for sale')),
                ('recipe_name', models.CharField(default='recipe', help_text='name of recipe used', max_length=60, verbose_name='recipe')),
                ('nitrogen_material', models.CharField(default='grass clips', max_length=25, verbose_name='nitrogen material used')),
                ('type_of_bucket_nitrogen', models.IntegerField(default=2, help_text='amount of buckets needed for one cubic yard', verbose_name='bucket size')),
                ('amount_nitrogen', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='amount of buckets used')),
                ('nitrogen_material_two', models.CharField(default='none', max_length=25, verbose_name='second nitrogen material used')),
                ('type_of_bucket_nitrogen_two', models.IntegerField(default=0, help_text='amount of buckets needed for one cubic yard', verbose_name='bucket size')),
                ('amount_nitrogen_two', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='amount of buckets used')),
                ('nitrogen_material_three', models.CharField(default='none', max_length=25, verbose_name='third nitrogen material used')),
                ('type_of_bucket_nitrogen_three', models.IntegerField(default=0, help_text='amount of buckets needed for one cubic yard', verbose_name='bucket size')),
                ('amount_nitrogen_three', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='amount of buckets used')),
                ('high_nitrogen_material', models.CharField(default='manure', max_length=25, verbose_name='high nitrogen material used')),
                ('type_of_bucket_high_nitrogen', models.IntegerField(default=2, help_text='amount of buckets needed for one cubic yard', verbose_name='bucket size')),
                ('amount_high_nitrogen', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='amount of buckets used')),
                ('high_nitrogen_material_two', models.CharField(default='none', max_length=25, verbose_name='second high nitrogen material used')),
                ('type_of_bucket_high_nitrogen_two', models.IntegerField(default=0, help_text='amount of buckets needed for one cubic yard', verbose_name='bucket size')),
                ('amount_high_nitrogen_two', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='amount of buckets used')),
                ('high_nitrogen_material_three', models.CharField(default='none', max_length=25, verbose_name='third high nitrogen material used')),
                ('type_of_bucket_high_nitrogen_three', models.IntegerField(default=0, verbose_name='bucket size')),
                ('amount_high_nitrogen_three', models.DecimalField(decimal_places=2, default=0, help_text='amount of buckets needed for one cubic yard', max_digits=8, verbose_name='amount of buckets used')),
                ('carbon_material', models.CharField(default='wood chips', max_length=25, verbose_name='carbon material used')),
                ('type_of_bucket_carbon', models.IntegerField(default=2, verbose_name='bucket size')),
                ('amount_carbon', models.DecimalField(decimal_places=2, default=0, help_text='amount of buckets needed for one cubic yard', max_digits=8, verbose_name='amount of buckets used')),
                ('carbon_material_two', models.CharField(default='none', max_length=25, verbose_name='Second carbon material used')),
                ('type_of_bucket_carbon_two', models.IntegerField(default=0, verbose_name='bucket size')),
                ('amount_carbon_two', models.DecimalField(decimal_places=2, default=0, help_text='amount of buckets needed for one cubic yard', max_digits=8, verbose_name='amount of buckets used')),
                ('carbon_material_three', models.CharField(default='none', max_length=25, verbose_name='third carbon material used')),
                ('type_of_bucket_carbon_three', models.IntegerField(default=0, verbose_name='bucket size')),
                ('amount_carbon_three', models.DecimalField(decimal_places=2, default=0, help_text='amount of buckets needed for one cubic yard', max_digits=8, verbose_name='amount of buckets used')),
                ('wide', models.DecimalField(decimal_places=2, default=0, help_text='in feet', max_digits=8, verbose_name='width of designated area')),
                ('length', models.DecimalField(decimal_places=2, default=0, help_text='in feet', max_digits=8, verbose_name='length of designated area')),
                ('tall', models.DecimalField(decimal_places=2, default=0, help_text='in feet', max_digits=8, verbose_name='height of compost')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Category')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.Supplier')),
                ('user', models.ForeignKey(help_text='person in working the pile', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='worked by')),
            ],
            options={
                'ordering': ['producer', '-pile_name', '-recipe_name', '-publish', '-update'],
            },
        ),
    ]
