# Generated by Django 2.2 on 2019-04-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fuel_station.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='fuel station name')),
                ('slug', models.SlugField(blank=True, help_text='leave blank or your-brand-name', null=True, unique=True)),
                ('invoice_number', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('fuel_type_pumped', models.CharField(choices=[('86', 'Gasoline-86'), ('89', 'Gasoline-89'), ('90', 'Gasoline-90'), ('D', 'Diesel'), ('FF', 'Flex fuel'), ('E', 'Electric'), ('EG', 'Hybrid'), ('S', 'Solar'), ('H', 'Hydrogen'), ('2C', 'Two Cycle fuels')], default='gasoline-86', max_length=2)),
                ('price_per_gal', models.DecimalField(decimal_places=3, max_digits=4)),
                ('amount_of_fuel', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuel_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_miles', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='miles ran')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('fueled_by', models.CharField(blank=True, max_length=120, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=fuel_station.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('content', models.TextField(verbose_name='Special Remark')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.TypeOfAsset')),
            ],
            options={
                'ordering': ['-timestamp', '-publish'],
            },
        ),
    ]
